-- 입양 시각 구하기(2)
-- 프로그래머스 오라클 lv4

SELECT A.HOUR,
    CASE WHEN B.COUNT IS NULL THEN 0
    ELSE B.COUNT END AS COUNT
FROM (SELECT (LEVEL-1) AS HOUR
     FROM DUAL
     CONNECT BY LEVEL <=24) A
     LEFT OUTER JOIN
     (SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR,
            COUNT(*) AS COUNT
     FROM ANIMAL_OUTS
     GROUP BY TO_NUMBER(TO_CHAR(DATETIME,'HH24')) ) B
     ON A.HOUR=B.HOUR
ORDER BY A.HOUR;