-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- 프로그래머스 LV3


SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, A.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    INNER JOIN
    (SELECT CAR_ID, COUNT(*) AS COUNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE EXTRACT(YEAR FROM START_DATE)=2022
      AND EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
      GROUP BY CAR_ID
      HAVING COUNT(*)>=5
     ) B
     ON A.CAR_ID=B.CAR_ID
WHERE EXTRACT(YEAR FROM START_DATE)=2022
AND EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
GROUP BY EXTRACT(MONTH FROM START_DATE), A.CAR_ID
HAVING COUNT(*)!=0
ORDER BY MONTH, A.CAR_ID DESC;


-- MYSQL
WITH RENTAL_COUNT AS
(
    SELECT CAR_ID, COUNT(*) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN CAST('2022-08-01' AS DATE) AND CAST('2022-10-31' AS DATE)
    GROUP BY CAR_ID
    HAVING COUNT >= 5
)
SELECT MONTH(START_DATE) AS MONTH, R.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C RIGHT OUTER JOIN RENTAL_COUNT R ON R.CAR_ID = C.CAR_ID
WHERE START_DATE BETWEEN CAST('2022-08-01' AS DATE) AND CAST('2022-10-31' AS DATE)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) != 0
ORDER BY MONTH, CAR_ID DESC;
