-- https://school.programmers.co.kr/learn/courses/30/lessons/293257

-- FISH_INFO : 잡은 물고기 정보 (길이가 10CM이하면 NULL)
-- FISH_NAME_INFO : 물고기 이름 정보
-- N.FISH_TYPE별 FISH_NAME과 FISH_COUNT(COUNT(I.*)) 출력
-- FISH_COUNT DESC

SELECT COUNT(ID) AS FISH_COUNT, FISH_NAME 
FROM FISH_INFO I JOIN FISH_NAME_INFO N ON I.FISH_TYPE=N.FISH_TYPE
GROUP BY N.FISH_TYPE, N.FISH_NAME
ORDER BY FISH_COUNT DESC;
