-- https://school.programmers.co.kr/learn/courses/30/lessons/59042

-- ANIMAL_INS, ANIMAL_OUTS : ANIMAL_ID
-- ANIMAL_ID, ANIMAL_TYPE, DATETIME(보호 시작일), INTAKE_CONDITION(보호시작상태), NAME, SEX_UPON_INTAKE(중성화 여부)
-- AMINAL_ID, ANIMAL_TYPE, DATETIME(입양일), NAME, SEX_UPON_OUTCOME(중성화여부)
-- ANIMAL_INS X, ANIAML_OUTS O 인 동물의 ANIMAL_ID, NAME을 출력 (ANIMAL_ID순)
-- ** A에는 있고 B에는 없는 데이터 조회 => A로 OUTER JOIN 수행 **

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;
